#!/bin/sh

# sudo pacman
alias pacman="sudo pacman"

# reflector -> sort pacman mirrors by age for most up to date packages
alias \
        reflector="sudo reflector --verbose --country 'United States' --sort age --save /etc/pacman.d/mirrorlist"

# up -> run reflector and then force package sync with update
alias \
        up="reflector && yay -Syyu"

# Use neovim for vim if present.
command -v nvim >/dev/null && alias vim="nvim" vimdiff="nvim -d"

# Verbosity and settings that you pretty much just always are going to want.
alias \
	bat="cat /sys/class/power_supply/BAT?/capacity" \
	cp="cp -iv" \
	mv="mv -iv" \
	rm="rm -v" \
	mkd="mkdir -pv" \
	yt="youtube-dl --add-metadata -i" \
	yta="yt -x -f bestaudio/best" \
	ffmpeg="ffmpeg -hide_banner"

# Colorize commands when possible.
alias \
	ls="ls -hN --color=auto --group-directories-first" \
	grep="grep --color=auto" \
	diff="diff --color=auto" \
	ccat="highlight --out-format=ansi"

# These common commands are just too long! Abbreviate them.
alias \
	ka="killall" \
	g="git" \
	trem="transmission-remote" \
	YT="youtube-viewer" \
	sdn="sudo shutdown -h now" \
	f="$FILE" \
	e="$EDITOR" \
	v="$EDITOR" \
	p="sudo pacman" \
	xi="sudo xbps-install" \
	xr="sudo xbps-remove -R" \
	xq="xbps-query"

# Some other stuff
alias \
	magit="nvim -c MagitOnly" \
	ref="shortcuts >/dev/null; source ${XDG_CONFIG_HOME:-$HOME/.config}/shortcutrc ; source ${XDG_CONFIG_HOME:-$HOME/.config}/zshnameddirrc" \
	weath="less -S ${XDG_DATA_HOME:-$HOME/.local/share}/weatherreport" \
	tmux="tmux -f ${XDG_CONFIG_HOME:-$HOME/.config}/tmux/tmux.conf"

# reflector -> sort pacman mirrors by age for most up to date packages
alias \
        reflector="sudo reflector --verbose --country 'United States' --sort age --save /etc/pacman.d/mirrorlist"

# up -> run reflector and then force package sync with update
alias \
        up="reflector && yay -Syyu"

# P99 midi synthesizer makes sound more gooder
alias \
        meq="fluidsynth -a pulseaudio -m alsa_seq -i -C off -R off -g 0.3 -s /home/kylok/Music/1mgm.sf2 &> /dev/null &"

